"use client";

/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/NEljUX7GE5y
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'
import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { CardContent, Card, CardTitle, CardDescription, CardHeader, CardFooter } from "@/components/ui/card"
import { DropdownMenuTrigger, DropdownMenuItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { Input } from "@/components/ui/input"
import { signOut, useSession } from "next-auth/react"

export function Dashboard() {

  const session = useSession();
  return (
    <div className="flex flex-col w-full min-h-screen">
      <header className="flex items-center h-16 px-4 border-b shrink-0 md:px-6">
        <nav className="flex-col hidden gap-6 text-lg font-medium md:flex md:flex-row md:items-center md:gap-5 md:text-sm lg:gap-6">
          <Link className="flex items-center gap-2 text-lg font-semibold" href="#">
            <SmileIcon className="w-6 h-6" />
            <span className="sr-only">MindMate AI</span>
          </Link>
          <Link className="font-bold" href="#">
            Home
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Progress
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Challenges
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Moments
          </Link>
        </nav>
        <div className="flex items-center w-full gap-4 md:ml-auto md:gap-2 lg:gap-4">
          <Button onClick={()=>signOut()} className="rounded-full ml-auto" size="icon" variant="ghost">
            <LogOutIcon className="w-4 h-4" />
            <span className="sr-only">Logout</span>
          </Button>
        </div>
      </header>
      <main className="flex flex-1 flex-col p-4 md:p-6">
        <div className="grid gap-6 md:grid-cols-[250px_1fr]">
          <Card className="p-0">
            <CardContent className="h-[calc(100vh_-_theme(spacing.16)_-_theme(spacing.16))] flex flex-col justify-center rounded-3xl border-0">
              <div className="flex items-center justify-center">
                <div className="grid gap-1 text-center">
                  <h1 className="text-4xl font-bold">Hello, {JSON.stringify(session.data?.user?.name)}!</h1>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Ready for your mental push-ups?</p>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center gap-4">
              <UserIcon className="w-8 h-8 rounded-full border" />
              <div className="grid gap-1">
                <CardTitle>John</CardTitle>
                <CardDescription>Hey! How can I help you today?</CardDescription>
              </div>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button className="ml-auto" size="icon" variant="ghost">
                    <MoreHorizontalIcon className="w-4 h-4" />
                    <span className="sr-only">Toggle menu</span>
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end">
                  <DropdownMenuItem>Settings</DropdownMenuItem>
                  <DropdownMenuItem>Help</DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </CardHeader>
            <CardContent>
              <div className="flex flex-col gap-2">
                <div className="flex items-start gap-2">
                  <UserIcon className="w-8 h-8 rounded-full border" />
                  <div className="bg-gray-100 p-4 rounded-xl text-sm dark:bg-gray-800/40">
  Hi! I&apos;m John, your mental fitness assistant. I&apos;m here to help you stay sharp, focused, and positive.
  You can talk to me about anything you like, whether it&apos;s a problem you&apos;re facing, an achievement you
  want to celebrate, or just to say hello!
</div>
                </div>
                <div className="flex items-start gap-2 flex-row-reverse">
                  <UserIcon className="w-8 h-8 rounded-full border" />
                  <div className="bg-gray-100 p-4 rounded-xl text-sm dark:bg-gray-800/40">
                    Ready for your first challenge? Let's get started!
                  </div>
                </div>
                <div className="flex items-start gap-2">
                  <UserIcon className="w-8 h-8 rounded-full border" />
                  <div className="bg-gray-100 p-4 rounded-xl text-sm dark:bg-gray-800/40">
  Remember, the most important thing is to be consistent. Even a little mental exercise every day can
  make a big difference over time. Let's keep up the good work!
</div>
                </div>
              </div>
            </CardContent>
            <CardFooter className="flex gap-4 mt-20">
              <form className="flex-1 ">
                <Input placeholder="Type your message..." />
              </form>
              <Button>Send</Button>
            </CardFooter>
          </Card>
        </div>
      </main>
    </div>
  )
}

function LogOutIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" />
      <polyline points="16 17 21 12 16 7" />
      <line x1="21" x2="9" y1="12" y2="12" />
    </svg>
  )
}


function MoreHorizontalIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="1" />
      <circle cx="19" cy="12" r="1" />
      <circle cx="5" cy="12" r="1" />
    </svg>
  )
}


function SmileIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M8 14s1.5 2 4 2 4-2 4-2" />
      <line x1="9" x2="9.01" y1="9" y2="9" />
      <line x1="15" x2="15.01" y1="9" y2="9" />
    </svg>
  )
}


function UserIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}
