"use client";

/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/5ybpxxJ4gKp
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { useState } from "react"
import { redirect } from "next/dist/server/api-utils"
import { useRouter } from "next/navigation"
import { signIn } from "next-auth/react"

export function LoginForm() {

  const [email,setEmail] = useState("");
  const [password,setPassword] = useState('');
  const [error,setError] = useState('');

  return (
    <form className="flex items-center justify-center h-screen">
      <Card className="w-full max-w-sm">
        <CardHeader className="text-center space-y-2">
          <CardTitle className="text-2xl font-bold">Login</CardTitle>
          <CardDescription>Enter your email below to login to your account.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input onChange={(e)=>setEmail(e.target.value)} id="email" placeholder="me@example.com" required type="email" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="password">Password</Label>
            <Input onChange={(e)=>setPassword(e.target.value)}  id="password" placeholder="******"  required type="password" />
          </div>
        </CardContent>
        <CardFooter className="flex justify-center flex-col space-y-4">
          <Button className="w-full">Login</Button>
          <Button  className="w-full" variant="outline">
            Login with Google
          </Button>
          <h1>Not a Member? <Link href="/register" className="text-blue-700">Register Here</Link></h1>
          {error && <p className="text-red-500">{error}</p>}
        </CardFooter>
        
      </Card>
    </form>
  )
}
