"use client"

/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/1KbaZsiNZIK
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Button } from "@/components/ui/button"
import  Link  from "next/link"
import { useState } from "react"
import axios from 'axios';
import { connectDb } from "@/lib/mongoDb"

export function RegisterForm() {

  const [name,setName] = useState('');
  const [email,setEmail] = useState("");
  const [password,setPassword] = useState('');
  const [employment,setEmployment] = useState('');

  const [error,setError] = useState('');

  const handleSubmit = async(e:any) =>{
    e.preventDefault();

    if(!name || !email || !password || !employment){
      setError('Please fill all the fields');
      return;
    }
    try{


      const res2 = await axios.post('/api/userExists',{
        email
      })

      const {user} = await res2.data;
      if(user){
        setError('User already exists');
        return;
      }
    const res =  await  axios.post('/api/register',{
      name,
      email, 
      employment,
      password,
      })

      if(res.status === 201){
        console.log(res.data.message)
        const form = e.target
        form.reset()
      }else{
        console.log('something went wrong')
      }
    }catch(err){
      console.log(err)
    }
  }
  return (
    <form className="flex items-center justify-center h-screen" onSubmit={handleSubmit}>
      <Card className="w-full max-w-sm">
        <CardHeader className="text-center space-y-2">
          <h1 className="text-2xl font-bold">Register</h1>
          <p className="text-sm text-gray-500 dark:text-gray-400">Fill in the details to create your account.</p>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="name">Name</Label>
            <Input id="name" onChange={(e)=>setName(e.target.value)} placeholder="Enter your name" required type="text" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input id="email" placeholder="me@example.com" onChange={(e)=>setEmail(e.target.value)} required type="email" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="employment">Employment Status</Label>
            <Select value={employment} onValueChange={setEmployment}>
              <SelectTrigger id="employment">
                <SelectValue placeholder="Select" />
              </SelectTrigger>
              <SelectContent position="popper">
                <SelectItem value="student">Student</SelectItem>
                <SelectItem value="private-job">Private Job</SelectItem>
                <SelectItem value="govt-employee">Government Employee</SelectItem>
                <SelectItem value="high-school-student">High School Student</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-2">
            <Label htmlFor="password">Password</Label>
            <Input onChange={(e)=>setPassword(e.target.value)} id="password" placeholder="******" required type="password" />
          </div>
        </CardContent>
        <CardFooter className="flex justify-center flex flex-col space-y-4">
          <Button className="w-full">Register</Button>
          <h1>Have an account? <Link href="/login" className="text-blue-700">Login Here</Link></h1>

          {error && <p className="text-red-500">Error: {error}</p>}
        </CardFooter>
      </Card>
    </form>
  )
}
